name: gait_env_new
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cuda-cudart=12.1.105
  - cuda-cudart_win-64=12.1.105
  - cuda-libraries=12.1.1
  - cuda-nvrtc=12.1.105
  - cuda-opencl=12.1.105
  - cuda-runtime=12.1.1
  - cuda-version=12.1
  - cudnn=9.10.2.21
  - expat=2.7.1
  - khronos-opencl-icd-loader=2024.10.24
  - libcublas=12.1.3.1
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcufft=11.0.2.54
  - libcurand=10.3.2.106
  - libcusolver=11.4.5.107
  - libcusparse=12.1.0.106
  - libffi=3.4.4
  - libnpp=12.1.0.40
  - libnvjitlink=12.1.105
  - libnvjpeg=12.2.0.2
  - libzlib=1.3.1
  - opencl-headers=2025.06.13
  - openssl=3.6.0
  - pip=25.2
  - python=3.10.18
  - sqlite=3.50.2
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - asttokens==3.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2022.12.7
      - cffi==2.0.0
      - charset-normalizer==2.1.1
      - chumpy==0.70
      - click==8.3.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.2
      - cycler==0.12.1
      - cython==3.1.4
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - filterpy==1.4.5
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fpdf==1.7.2
      - fsspec==2024.6.1
      - humanfriendly==10.0
      - idna==3.4
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.2.0
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - mmpose==1.3.2
      - model-index==0.1.11
      - mpmath==1.3.0
      - munkres==1.1.4
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.3
      - numpy==1.26.4
      - onnxruntime-gpu==1.18.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - opt-einsum==3.4.0
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pickleshare==0.7.5
      - pillow==11.0.0
      - pip-check-reqs==2.5.5
      - pipreqs==0.5.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - pure-eval==0.2.3
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pymodbustcp==0.3.0
      - pyparsing==3.2.5
      - pyrealsense2==2.56.5.9235
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywin32==311
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.28.2
      - rich==13.4.2
      - rpds-py==0.30.0
      - scipy==1.15.3
      - setuptools==60.2.0
      - shapely==2.1.2
      - six==1.17.0
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - tinycss2==1.4.0
      - tomli==2.3.0
      - torch==2.1.0+cu121
      - torchaudio==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - tornado==6.5.4
      - tqdm==4.65.2
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ultralytics==8.3.240
      - urllib3==1.26.13
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - yarg==0.1.9
prefix: C:\Users\LOQ\miniconda3\envs\gait_env_new
